name: Crypto Twitter Bot

on:
  schedule:
    - cron: '0 * * * *'  # Every hour on the hour
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'If true will NOT post. Default=true for manual runs.'
        required: false
        default: 'true'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      # For manual workflow_dispatch this uses the input; for schedule (no input) this falls back to 'false'
      DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Show workspace & bot
      run: |
        echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
        pwd
        ls -la
        echo "---- bot.py (first 200 lines) ----"
        sed -n '1,200p' poster.py || true

    - name: Run poster
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        DRY_RUN: ${{ env.DRY_RUN }}
      run: |
        python poster.py

    - name: Upload logs & image artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: bot-outputs
        path: |
          bot.log
          crypto_chart.png
